### ISSUE TITLE
Unable to create conda environment

### ISSUE THREAD

**Issue by lpereira89** [bxuecarnegie/deepec#1]
Hello,
I tried to install deepec to use E2P2, however I was unable to create the conda environment. I followed the instructions to create it using the file (no success) and also manually. When doing it manually, it seems like the problem is `tensorflow=1.5.0`, that fails recurrently. 
Could someone please advise what to do? Might this happen because of a version issue?
Thank you!
Lara

**Comment by bxuecarnegie** [comment]
Hi Lara,

Without knowing your platform and what errors you're encountering, it's going to be harder for me to help you. I've added in an "environment-hpc.yml" that was set up by our IT on HPC and is working so that might be helpful for you. I've also corrected the readme git clone address since that was incorrectly pointed to the original repo.

Best,
Bo

**Comment by ShuaiNIEgithub** [comment]
Hi Bo,

I am confident that the issues raised by Lara are real and potentially widespread.


`conda env create -f environment.yml
Channels:
 - bioconda
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
/ ['/data1/nieshuai/software/miniconda3/envs/deepec/bin/python', '-m', 'pip', 'install', '-U', '-r', '/data1/nieshuai/software/E2P2/deepec/condaenv.xymfudbj.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting numpy==1.16.2 (from -r /data1/nieshuai/software/E2P2/deepec/condaenv.xymfudbj.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)

Pip subprocess error:
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffbcad5de48>: Failed to establish a new connection: [Errno 101] 网络不可达',)': /packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffbcad63240>: Failed to establish a new connection: [Errno 101] 网络不可达',)': /packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl
Exception:
Traceback (most recent call last):
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/http/client.py", line 467, in read
    n = self.readinto(b)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/http/client.py", line 511, in readinto
    n = self.fp.readinto(b)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 334, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/download.py", line 878, in unpack_url
    progress_bar=progress_bar
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/download.py", line 702, in unpack_http_url
    progress_bar)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/download.py", line 946, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/download.py", line 639, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/download.py", line 607, in written_chunks
    for chunk in chunks:
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 159, in iter
    for x in it:
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_internal/download.py", line 596, in resp_read
    decode_content=False):
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/data1/nieshuai/software/miniconda3/envs/deepec/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

failed

CondaEnvException: Pip failed

`
Thank you!
Shuai

**Comment by bxuecarnegie** [comment]
Hi Lara,

An updated environment.yml has been uploaded, this was tested on Linux. I will be closing this ticket for the time being but feel free reopen it if you still have issues.

Best,
Bo
